<a href="https://colab.research.google.com/github/dwii3830-spec/Jawaban-Soal-MetNumerik-11.1-11.28/blob/main/Soal%2011.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal 11.4 - Verifikasi Cholesky Decomposition dari Example 11.2
Membuktikan bahwa [L][L]^T = [A]

In [1]:
"""
Matriks dari Example 11.2:
[A] = [[2, 1, 1], [1, 3, 2], [1, 2, 2]]
"""
import numpy as np

def cholesky_decomposition(A):
    """Dekomposisi Cholesky manual."""
    n = A.shape[0]
    L = np.zeros((n, n))
    for i in range(n):
        for j in range(i+1):
            s = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:
                val = A[i][i] - s
                if val <= 0:
                    raise ValueError("Matriks tidak positif definit!")
                L[i][j] = np.sqrt(val)
            else:
                L[i][j] = (A[i][j] - s) / L[j][j]
    return L

# Matriks simetris positif definit (Example 11.2 dari buku)
A = np.array([[2.0, 1.0, 1.0],
              [1.0, 3.0, 2.0],
              [1.0, 2.0, 2.0]])

print("=" * 50)
print("Soal 11.4 - Verifikasi Cholesky Decomposition")
print("=" * 50)
print("\nMatriks A:")
print(A)

L = cholesky_decomposition(A)
print("\nMatriks L (lower triangular):")
print(np.round(L, 6))

LLT = L @ L.T
print("\n[L][L]^T =")
print(np.round(LLT, 6))

print("\nApakah [L][L]^T == [A]?", np.allclose(LLT, A))
print("Error maksimum:", np.max(np.abs(LLT - A)))

Soal 11.4 - Verifikasi Cholesky Decomposition

Matriks A:
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 2. 2.]]

Matriks L (lower triangular):
[[1.414214 0.       0.      ]
 [0.707107 1.581139 0.      ]
 [0.707107 0.948683 0.774597]]

[L][L]^T =
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 2. 2.]]

Apakah [L][L]^T == [A]? True
Error maksimum: 4.440892098500626e-16
