<a href="https://colab.research.google.com/github/dwii3830-spec/Jawaban-Soal-MetNumerik-11.1-11.28/blob/main/Soal_11_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal 11.2 - Invers matriks menggunakan dekomposisi LU dan unit vectors
Berdasarkan sistem dari Example 11.1:

In [1]:
"""
[A] = [[0.8, -0.4, 0], [-0.4, 0.8, -0.4], [0, -0.4, 0.8]]
"""
import numpy as np
from scipy.linalg import lu

def lu_inverse(A):
    """Hitung invers matriks menggunakan dekomposisi LU dan unit vectors."""
    n = A.shape[0]
    A_inv = np.zeros((n, n))
    # Unit vectors sebagai RHS
    for i in range(n):
        e = np.zeros(n)
        e[i] = 1.0
        A_inv[:, i] = np.linalg.solve(A, e)
    return A_inv

A = np.array([[0.8, -0.4, 0.0],
              [-0.4, 0.8, -0.4],
              [0.0, -0.4, 0.8]])

A_inv = lu_inverse(A)

print("=" * 50)
print("Soal 11.2 - Invers Matriks via LU Decomposition")
print("=" * 50)
print("\nMatriks A:")
print(A)
print("\nInvers A (via LU + unit vectors):")
print(np.round(A_inv, 6))

# Verifikasi: A @ A_inv = I
product = A @ A_inv
print("\nVerifikasi A @ A_inv (seharusnya = I):")
print(np.round(product, 10))

# Bandingkan dengan numpy
print("\nInvers A (via numpy):")
print(np.round(np.linalg.inv(A), 6))

Soal 11.2 - Invers Matriks via LU Decomposition

Matriks A:
[[ 0.8 -0.4  0. ]
 [-0.4  0.8 -0.4]
 [ 0.  -0.4  0.8]]

Invers A (via LU + unit vectors):
[[1.875 1.25  0.625]
 [1.25  2.5   1.25 ]
 [0.625 1.25  1.875]]

Verifikasi A @ A_inv (seharusnya = I):
[[ 1.  0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]

Invers A (via numpy):
[[1.875 1.25  0.625]
 [1.25  2.5   1.25 ]
 [0.625 1.25  1.875]]
